project:
  type: website
  output-dir: docs
  resources:
    - "assets"

website:
  title: "Hannah Rozenbaum"
  navbar:
    background: primary
    search: false
    left:
      - href: index.qmd
        text: "Home"
      - text: "Portfolio"
        menu:
          - href: projects.qmd
            text: "Technical Projects"
          - href: essays.qmd
            text: "Socio-Technical Risk Assessments"
          - href: data-vis-and-creative-work.qmd
            text: "Data Visualization & Creative Work"
      - href: resume.qmd
        text: "Resume"
      - href: contact.qmd
        text: "Contact"

format:
  html:
    theme: 
      - lux
      - styles.css
    toc: true
    
execute:
  freeze: auto